<?php
$warzon =[
  "capacidad de jugadores" => "n+50",
  "tamaño de mapa" => 9.5,
  "numero de ubicasiones" => 17,
  "cauntos maps tiene" => 5,
  "cuantos modos de juego tiene" => 2,
  "en que año enpesaron" => 2003,
  "nombre de el creador o empresa" => "Gray Matter Interactive",
  "dinero total ganado" => "390 millones de dólares ",
  "total de jugadores" => "250.000 y 430.000 jugadores",
  "que tipos de zonas tienen" => "gas mostasa",
  "como se llega al batle royal" => "en un avion",
  "como ganas escudo" => "con placas de blindaje",
  "cantidad de vida" => 100,
  "cantidad de escudo" => 150,
  "numero de personas que pueden jugar" => 4,
  "tiempo de inicio aprox de una partida" => "varia",
  "cantidad de servidores" => 6,
  "cuanto gana al dia" =>"225 millones",
  "tipos de combates" => "todo tipo",
  "tipos de armas" => "normales",
  "en donde se puede jugar" => "pc xbox playstation telefono",
];
  $fornite[
  "capacida de jugadores" => "n100",
  "tamaño de mapa" => 5.4,
  "numero de ubicasiones" => 14,
  "cuantos mapas tiene" => 1,
  "cuantos modos tiene" => 3,
  "en que año enpesaron" => "21 de julio de 2017"
  "nombre de el creador o empresa" => "epic games"
  "dinero total ganado" => "5.600 millones de dolares"
  "total de jugadores" => "400 millones de jugadore registrados"
  "que tipos de zonas tienen" => "tormentas"
  "como se llega al batle royal" => "en un camion"
  "como ganas escudo" => "con bebidas"
  "cantidad de vida" => 100
  "cantidad de escudo" => 150
  "numero de personas que pueden jugar" => 4
  "tiempo de inicio aprox de una partida" => "1 m.n"
  "cantidad de servidores" => 6
  "cuanto gana al dia" =>6 "millones de dolares"
  "tipos de combates" => "todo tipo"
  "tipos de armas" => "normales"
  "en donde se puede jugar" => "pc xbox playstation switch"
  ];
  $freefire =[
  "capacidad de jugadores" => 100,
  "tamaño de mapa" => 10.5,
  "numero de ubicasiones" => 15,
  "cauntos maps tiene" => 6,
  "cuantos modos de juego tiene" => 3,
  "en que año enpesaron" => 2017,
  "nombre de el creador o empresa" => "Garena",
  "dinero total ganado" => "83 millones ",
  "total de jugadores" => "1000 millones",
  "que tipos de zonas tienen" => "zona toxica",
  "como se llega al batle royal" => "en un avion",
  "como ganas escudo" => "con setas",
  "cantidad de vida" => 100,
  "cantidad de escudo" => 100,
  "numero de personas que pueden jugar" => 4,
  "tiempo de inicio aprox de una partida" => "varia",
  "cantidad de servidores" => 6,
  "cuanto gana al dia" =>"50 millones",
  "tipos de combates" => "todo tipo",
  "tipos de armas" => "normales",
 "en donde se puede jugar" => "pc telefono",
  ];
  $apex =[
  "capacidad de jugadores" => 100,
  "tamaño de mapa" => 7.5,
  "numero de ubicasiones" => 15,
  "cauntos maps tiene" => 3,
  "cuantos modos de juego tiene" => 1,
  "en que año enpesaron" => 2019,
  "nombre de el creador o empresa" => "Respawn Entertainment ",
  "dinero total ganado" => "2.000 millones de dólares",
  "total de jugadores" => "600.000 jugadores",
  "que tipos de zonas tienen" => "tormenta roja",
  "como se llega al batle royal" => "por una tirolesa",
  "como ganas escudo" => "baterias",
  "cantidad de vida" => 100,
  "cantidad de escudo" => 150,
  "numero de personas que pueden jugar" => 4,
  "tiempo de inicio aprox de una partida" => "varia",
  "cantidad de servidores" => 6,
  "cuanto gana al dia" =>"25 millones",
  "tipos de combates" => "todo tipo",
  "tipos de armas" => "laser",
 "en donde se puede jugar" => "pc xbox play",
  ];

